---
name: CMake

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    # run at 15:30 on day-of-month 7.
    - cron: '30 15 7 * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  unix:
    strategy:
      fail-fast: false

      matrix:
        platform:
          - os: macos-latest
            compiler: llvm-22
          - os: macos-latest
            compiler: gcc-16
          - os: ubuntu-26.04
            compiler: llvm-22
          - os: ubuntu-26.04
            compiler: gcc-16

        variant:
          - compile_commands.json
          - disabled_modules
          - fresh

    name: ${{ matrix.platform.os }} / ${{ matrix.platform.compiler }} / ${{ matrix.variant }}
    runs-on: ${{ matrix.platform.os }} # -latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup build environment
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "^4.4.2"
          ninjaVersion: "~1.13.0"

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.platform.compiler }}

      - name: Configure CMake custom preset
        run: make ${{ matrix.variant }}

      - name: Build CMake custom preset
        run: make build

      - name: Install custom project
        run: make install

      - name: Test custom examples
        run: make ctest

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup build environment
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "^4.4.2"
          ninjaVersion: "~1.13.0"

      - name: Setup MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: x64

      - name: Configure CMake
        run: cmake --preset ${{env.BUILD_TYPE}} --log-level=VERBOSE -D BOOST_USE_MODULES=ON

      - name: Build
        # Build your program with the given configuration
        run: cmake --build --preset ${{env.BUILD_TYPE}}

      - name: Install
        # Install the project artefacts to CMAKE_INSTALL_PREFIX
        run: cmake --install ${{github.workspace}}/build/${{env.BUILD_TYPE}} --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build/${{env.BUILD_TYPE}}
        # Execute tests defined by the CMake configuration, but needs to find_package(Boost)!
        run: ctest -C ${{env.BUILD_TYPE}}
